//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LorealAvaloniaUI.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LorealAvaloniaUI.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0:f}.
        /// </summary>
        public static string CleanupDateFormat {
            get {
                return ResourceManager.GetString("CleanupDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of files deleted: {0}.
        /// </summary>
        public static string DeletedFileCountFormat {
            get {
                return ResourceManager.GetString("DeletedFileCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the deleted files: {0} GB.
        /// </summary>
        public static string DeletedFileSizeFormat {
            get {
                return ResourceManager.GetString("DeletedFileSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Manage space.
        /// </summary>
        public static string DOFCButtonText {
            get {
                return ResourceManager.GetString("DOFCButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string DownloadsTitle {
            get {
                return ResourceManager.GetString("DownloadsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB Free.
        /// </summary>
        public static string FreeStorageTextFormat {
            get {
                return ResourceManager.GetString("FreeStorageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URGENT: Critical Low Disk Space Alert!.
        /// </summary>
        public static string HeaderMessageCritical {
            get {
                return ResourceManager.GetString("HeaderMessageCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Status.
        /// </summary>
        public static string HeaderMessageNormal {
            get {
                return ResourceManager.GetString("HeaderMessageNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Files Cache.
        /// </summary>
        public static string OfficeFilesCacheTitle {
            get {
                return ResourceManager.GetString("OfficeFilesCacheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncache local space.
        /// </summary>
        public static string OneDriveButtonText {
            get {
                return ResourceManager.GetString("OneDriveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string OutlookButtonText {
            get {
                return ResourceManager.GetString("OutlookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB available of {1} GB.
        /// </summary>
        public static string PreviousFreeSpaceFormat {
            get {
                return ResourceManager.GetString("PreviousFreeSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: {0} GB.
        /// </summary>
        public static string SizeDisplay {
            get {
                return ResourceManager.GetString("SizeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB Used of {1} GB.
        /// </summary>
        public static string StorageUsageTextFormat {
            get {
                return ResourceManager.GetString("StorageUsageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous clean up summary:.
        /// </summary>
        public static string SummaryHeader {
            get {
                return ResourceManager.GetString("SummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of OneDrive files uncached through selection: {0}.
        /// </summary>
        public static string UncachedFileCountFormat {
            get {
                return ResourceManager.GetString("UncachedFileCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the OneDrive uncached files through selection: {0} GB.
        /// </summary>
        public static string UncachedSpaceFormat {
            get {
                return ResourceManager.GetString("UncachedSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system is running critically low on storage, which may impact performance and stability. We highly recommend you immediately free up space. Please navigate through the Downloads, One Drive, and Office Cache sections to clean up your disk..
        /// </summary>
        public static string UserInstructionMessageCritical {
            get {
                return ResourceManager.GetString("UserInstructionMessageCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please navigate through the Downloads, One Drive, and Office Cache sections to clean up your disk..
        /// </summary>
        public static string UserInstructionMessageNormal {
            get {
                return ResourceManager.GetString("UserInstructionMessageNormal", resourceCulture);
            }
        }
    }
}
